# Generated by Django 5.2.5 on 2025-08-28 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=500, verbose_name='Résumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image')),
                ('category', models.CharField(choices=[('web', 'Développement Web'), ('design', 'Design & UX'), ('tech', 'Technologies'), ('tips', 'Conseils & Astuces'), ('news', 'Actualités')], default='web', max_length=20, verbose_name='Catégorie')),
                ('author', models.CharField(default='Mohamed SARE', max_length=100, verbose_name='Auteur')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
