# Generated by Django 5.2.5 on 2025-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=500, verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image principale')),
                ('category', models.CharField(choices=[('web', 'Développement Web'), ('mobile', 'Application Mobile'), ('desktop', 'Application Desktop'), ('design', 'Design & UI/UX'), ('ai', 'Intelligence Artificielle'), ('game', 'Jeux Vidéo'), ('other', 'Autre')], default='web', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('in_progress', 'En cours'), ('planned', 'Planifié'), ('on_hold', 'En pause')], default='completed', max_length=20, verbose_name='Statut')),
                ('technologies', models.TextField(help_text='Une par ligne ou séparées par des virgules', verbose_name='Technologies utilisées')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Lien GitHub')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Lien en ligne')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Lien démo')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet en vedette')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
