# Generated by Django 5.2.5 on 2025-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms_portfolio', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Application Web'), ('mobile', 'Application Mobile'), ('desktop', 'Application Desktop'), ('design', 'Design & UI/UX'), ('ai', 'Intelligence Artificielle'), ('game', 'Jeux Vidéo'), ('other', 'Autre')], default='web', max_length=20, verbose_name='Catégorie'),
        ),
    ]
