# Generated by Django 4.2.26 on 2025-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ms_portfolio", "0005_skillcategory_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="CV - Mohamed SARE",
                        max_length=200,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Format PDF recommandé",
                        upload_to="cv/",
                        verbose_name="Fichier CV",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si actif, le CV sera disponible au téléchargement",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'upload"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
            ],
            options={
                "verbose_name": "CV",
                "verbose_name_plural": "CV",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
